### ISSUE TITLE
fntファイル1行目にあるfaceに空白が入っていると落ちる。

### ISSUE THREAD

**Issue by hirmiura** [hirmiura/starsector-mod-Font_Sika_for_Insignia#7]
fntファイル1行目にあるfaceに空白が入っていると落ちる。

~~再現方法1~~
~~Mplus1から作ったビットマップフォントでInsigniaを置き換えると~~
~~U+03BC(μ)が足りないので起動時に落ちる。~~

~~再現方法2~~
~~Starsectorに同梱されているInsigniaLT(lte50549.ttf)からU+03BC(μ)だけを~~
~~抜いたビットマップフォントで置き換えると起動時に落ちる。~~

![insigniaLTwithoutMu](https://user-images.githubusercontent.com/6115787/150135205-90b00b59-95cd-4df0-bcf9-99ce173808fa.png)

**Comment by hirmiura** [comment]
```
27668 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.ArrayIndexOutOfBoundsException: 1
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.fs.graphics.A.D.o00000(Unknown Source)
	at com.fs.graphics.A.D.o00000(Unknown Source)
	at com.fs.starfarer.loading.ResourceLoaderState.init(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by hirmiura** [comment]
コードに不足がない源真ゴシックでも落ちる。
不足のないInsigniaでも落ちるから生成オプションが悪い？

**Comment by hirmiura** [comment]
切り分けできた。fntファイル1行目にあるfaceに空白が入っていると落ちる。
○ info face="InsigniaLT" size=15
× info face="Insignia LT" size=15
糞仕様

**Comment by hirmiura** [comment]
2b5617fb8c5cd4985d680d8377ef149d17ca4e59 で修正した。
